#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
#+ Between each iteration of the loop, add a sleep 2.
#+ ctrl+c (killed) the Bash script in the example.
while true;
do
       echo "To infinity and beyond"
       sleep 2
done