#!/usr/bin/env bash
# script to display "Best School" 10 times but the  9th iteration display "Hi"
i=0
while [ $i -lt 10 ];
do
      echo "Best School"
      (( i=i+1 ))
      if [ $i -eq 9 ];
      then
	  echo "Hi"
      fi
done