#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12.
#+ display hours from 0 to 12.
#+ Must use the while loop.
i=0
while [ $i -lt 13 ]; do
    echo "Hour: $i"
    j=1
    while [ $j -lt 60 ]; do
	echo $j
	(( j=j+1 ))
    done
    (( i=i+1 ))
done
